### ISSUE TITLE
|の後に絶対パスでコマンドを実行するとcommnad not foundとなる

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#12]
事案
|の後に絶対パスでコマンドを実行するとcommnad not foundとなる

事案詳細
|の後に絶対パスでコマンドを実行するとcommnad not foundとなる
```
minishell$ /bin/ls | /bin/ls
bash: /bin/ls: commnad not found
```
以下は問題ない。
```
minishell$ /bin/ls ; /bin/ls
minishell$ /bin/ls
```

再現手順
[minishell]
```
minishell$ /bin/ls | /bin/ls
bash: /bin/ls: commnad not found
```

**Comment by Yoshiki-Iwasa** [comment]
修正済み。

原因：PATH の変更をコマンドライン読み込みの直後に行っていたため先頭のコマンドに対してしかPATH の変更が効いていなかった。PATH の変更を各コマンド実行前に移動することで解消。

**Comment by hiroin** [comment]
修正を確認しました。
