### ISSUE TITLE
Ctrl + Cを押下した際の動作相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#15]
事案
Ctrl + C押下した際の動作相違

事案詳細
bashの場合、Ctrl + Cを押下した場合「^C[Enter]」と表示されるが、minishellは「[Enter]」だけが表示される。

[bash]
```
$ ^C ← Ctrl + C
$ ls^C ← lsの後Ctrl + C
$
```
[minishell]
```
minishell$ ← Ctrl + C
minishell$ ← lsの後Ctrl + C
minishell$
```

**Comment by Yoshiki-Iwasa** [comment]
ほんとだ。。。。
これ自分の環境のbash だと^C ださないんですよね
修正しておきます

**Comment by Yoshiki-Iwasa** [comment]
修正済み（VM でためしました）

**Comment by hiroin** [comment]
修正を確認しました。
