### ISSUE TITLE
シェルがコマンド待ちの状態におけるCtrl + Dを押下した際の動作相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#16]
事案
Ctrl + Dを押下した際の動作相違

事案詳細
bashの場合、シェルがコマンド待ちの状態($の状態)において、Ctrl + Dを押下した場合「exit[Enter]」と表示されシェルを終了するが、minishellの場合、「[Enter]」のみが表示されシェルが終了する。

[bash]
```
$ exit ← Ctrl + D
```
[minishell]
```
minishell$ ← Ctrl + D
```

**Comment by Yoshiki-Iwasa** [comment]
修正しました。

**Comment by hiroin** [comment]
修正を確認しました。
