### ISSUE TITLE
コマンドの入力の途中でCtrl + Dを2回押下した際の動作相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#17]
事案
コマンドの入力の途中でCtrl + Dを2回押下した際の動作相違

事案詳細
bashの場合、コマンドの入力の途中でCtrl + Dを何回押しても何も怒らないが、minishellの場合、Ctrl + Dを2回押した時点でシェルが終了する。

[bash]
```
$ ls ← Ctrl + Dを押しまくっても何も起こらない
```
[minishell]
```
minishell$ ls ← Ctrl + Dを2回押した時点でシェルが終了する
$

**Comment by Yoshiki-Iwasa** [comment]
苦戦してます。
Ctrl  + C や　Ctrl + \ と違って　Ctrl + D　はプロセスにシグナルを送るのではなく　EOF を打ち込むだけなのでどうハンドルすればいいかわかりません。

Ctrl  + C や　Ctrl + \ 　は　プロセスに固有のシグナルを送るので、signal 関数で　トラップして共同を変更できたんですが、Ctrl + D  が　送る　EOF　を与えられた関数のみでトラップするのは無理じゃないかなと思い始めてます

**Comment by Yoshiki-Iwasa** [comment]
これちょっと相談させてほしいです。実装厳しそうです

 Ctrl + D  は Ctrl + C  などとは違い、シグナルは送らず単にEOF を送るだけです。　なので、Ctrl + D  を感知するまではできても、無視するというのは、今回許可されている関数ではできない気がします。
キーボードの操作を完治するシステムコールが必要だと思いました。

**Comment by hiroin** [comment]
了解しました。
自分がctrl + dの動きを理解してないので、夜に動作を理解しつつ実装を考えます。

息子のお迎えの帰りに鹿に遭遇しました。

2020年9月2日(水) 15:10 Yoshiki-Iwasa <notifications@github.com>:

**Comment by Yoshiki-Iwasa** [comment]
ありがとうございます。自分も粘ってみます。　

一回目の Ctrl + D  による　"^D" はどうしても出ると思います。

野生の鹿って意外と怖いですよ
ね笑

**Comment by Yoshiki-Iwasa** [comment]
修正済み。

Ctrl + D を二回押したあとは、すでに入力したコマンドは削除できませんが追加入力はできる仕様にしました。
Ctrl + C で新たな次のコマンドラインに移動できます。

**Comment by hiroin** [comment]
仕様修正確認しました!
