### ISSUE TITLE
catでEOL待ちの状態におけるCtrl + C押下時動作相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#18]
事案
catでEOL待ちの状態におけるCtrl + C押下時動作相違

事案詳細
bashの場合、catコマンドの実行後、Ctrl + Cを押すと、^Cを表示してcatコマンドが終了するが、minishellの場合、catコマンドが終了するのみとなる。

[bash]
```
$ cat ← Ctrl + C
^C
$
```
[minishell]
```
$ cat ← Ctrl + C
$

```

**Comment by Yoshiki-Iwasa** [comment]
修正済み

**Comment by hiroin** [comment]
修正を確認しました。
