### ISSUE TITLE
catでEOL待ちの状態におけるCtrl + \押下時動作相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#19]
事案
catでEOL待ちの状態におけるCtrl + \押下時動作相違

事案詳細
bashの場合、catコマンドの実行後、Ctrl + \を押すと、^\Quit (core dumped)を表示してcatコマンドが終了するが、minishellの場合、catコマンドが終了するのみとなる。

[bash]
```
$ cat ← Ctrl + \
^\Quit (core dumped)
$
```
[minishell]
```
$ cat ← Ctrl + \
$
```

**Comment by Yoshiki-Iwasa** [comment]
bash だとコマンドによって出力が違います。これは一体何が違うのでしょう

```
bash-3.2$ wc
^\Quit: 3

bash-3.2$ sort
^\bash-3.2$ 
```

**Comment by Yoshiki-Iwasa** [comment]
一応、すべての場合にたいして、^\Quit: 3　を出力するようにしました。

**Comment by hiroin** [comment]
岩佐さん…いいところに気がついちゃってます。
まず
https://www.ipa.go.jp/security/awareness/vendor/programmingv1/b07_06.html
を読んでください。

自分もMACのbash3.2のsortがcoredumpしないことを確認しました。※ちなみにLinuxのsortはcoredumpします。
Linuxのbash4.0の場合
```
$ cat
^\Quit (core dumped)
```
と表示されるのですが、core dumpしないように設定すると、core dumpedのメッセージが消えます。
```
$ ulimit -c 0 ← coreを生成しないように設定する
$ cat
^\Quit
```
この事実と、上記URLの情報から推測すると、MACのsortはcore dumpを生成しないようにしているコマンドなのだと思います。

core dumpを生成する場合
```
^\Quit (core dumped)
```
core dumpを生成しない場合
```
^\Quit
```
と表示されるのが正しいです。
が…、core dumpを生成したのかしないのかをどう判断しているのかわかりませんでした。
というのは、core dumpの生成に失敗しても、core dumpしようとした場合には
```
^\Quit (core dumped)
```
と表示されるのです。
そして、core dumpの生成に失敗した場合、Ubuntuは/var/log/apport.logにログを吐きます。
```
ERROR: apport (pid 22291) Tue Sep  1 15:17:37 2020: called for pid 22290, signal 3, core limit 0, dump mode 1
```

シグナルは投げっぱなしで、投げ先のコマンドからの返り値を受け取ることはないと思っているので、投げ先のコマンドが「coredumpを生成しました」と教えてくれるわけではない…と思っています。

とすると…、いったいどうやってcore dumpを生成「しようとした」ことを検知しているのかわかりません。

**Comment by Yoshiki-Iwasa** [comment]
すべてのパターンにおいて
```
^\Quit (core dumped)
```
と表示するようにしました

**Comment by hiroin** [comment]
ありがとうございます!
teratailでcore dumpedしたことを検知できる方法があるかを聞いてみますー

**Comment by hiroin** [comment]
teratailに投稿しました。
https://teratail.com/questions/289693

**Comment by hiroin** [comment]
teratailに自分が知りたかったとても的確な回答がきました。
https://teratail.com/questions/289693#reply-410636

おそらく、command_shell.cのexec_shell_command関数のwait関数の後に
```
if(WTERMSIG(status))
{
	if(WCOREDUMP(status))
	{
		//core dumpを取得したフラグをたてる
	}
}
```
を追加し、command_shell.cのsig_handle_bs関数において、core dumpを取得したフラグをチェックしてフラグがtureであれば「 (core dumped)」と表示する…になります。

**Comment by Yoshiki-Iwasa** [comment]
ありがとうございます！　修正しました！

すごい、wait にコアダンプを感知できるマクロがあったんですね！

一応修正はしたのですが、自分のVMでは ulimit -c 0 を実行してもコアダンプを生成してしまい、コアダンプを生成しないときちゃんと ```^\Quit ``` で終われているかは確認できてないです。。。。

**Comment by hiroin** [comment]
修正を確認しました。
ulimit -c 0を実行しても、自分の環境でもコアダンブを生成してしまいました…
コアダンブを生成する場所を変更したら、コアダンプを生成しなくなったので、それで確認しました。
