### ISSUE TITLE
ダブルクォーテーションによる展開ルールの相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#2]
事案
ダブルクォーテーションによる展開ルールの相違

事案詳細
複数の"で囲まれたときの展開ルールが異なる。
[minishell]
```
$ echo """${USER}"""
"user42"
```
[bash]
```
$ echo """${USER}"""
user42
```

推定
bashは以下のように""を展開する
"""${USER}""" →　"${USER}"を展開
""user42"" → "user42"を展開
"user42" → "user42"を展開
user42

推定理由
$ echo "${USER}""
と入力すると、
$ echo "${USER}""
\>
と入力待ちになる。ここで、"を入力すると
$ echo "${USER}""
\> "
user42
となる。
つまり、"だけの場合、"が来るまで待つ仕様になってることから、""でワンセットであると推定した。
"を出力したい場合は、\\"と"をエスケープする必要がある。

再現手順
[minishell]
```
minishell$ echo "${USER}"
user42
minishell$ echo "${USER}""
user42"
minishell$ echo ""${USER}""  
user42
minishell$ echo """${USER}"""
"user42"
minishell$ echo " """${USER}""" "
 "user42"
```

[bash]
```
$ echo "${USER}"
user42
$ echo ""${USER}""
user42
$ echo """${USER}"""
user42
$ echo """"${USER}""""
user42
$ echo " """${USER}""" "
 user42 
$ echo ""${USER}"
> ^C
$ echo "${USER}""
> "
user42

$ echo \""${USER}"
"user42
```

**Comment by Yoshiki-Iwasa** [comment]
”　や　’　が足りないときに入力待になる問題については、サブジェクトに、
`’ and " should work like in bash except for multiline commands`
と書いてあることから対応しなくていいかなと思いました。``

クオートが足りない場合は、エラーメッセージを表示して次の入力にすすむって仕様にしようかなと思ってます

**Comment by hiroin** [comment]
神谷 @甲府のイオンモールです。

確かにmultilineは実装しない…、クォートが足りないときはmultilineになるので対応しなくてOKです！

2020年8月30日(日) 10:19 Yoshiki-Iwasa <notifications@github.com>:

**Comment by Yoshiki-Iwasa** [comment]
修正済み。

原因　：複数クオートの想定をしていなかった

**Comment by hiroin** [comment]
修正を確認しました。
