### ISSUE TITLE
ダブルクォーテーションで囲われた中の文字のエスケープ処理不備

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#21]
事案
ダブルクォーテーションで囲われた中の文字のエスケープ処理不備

事案詳細
""で囲われた中で"や$を表示したい場合は、\でエスケープする。
例えば、"を表示したい場合は"\""、$を表示したい場合は、"\$"とする。
しかし、minishellにおいて、\がエスケープ文字として機能していない。

[bash]
```
$ cat "\""
cat: '"': No such file or directory
$ cat "\$"
cat: '$': No such file or directory
```
[minishell]
```
minishell$ cat "\""
bash : Bad quotation
minishell$ cat "\$"
cat: '\': No such file or directory
```

**Comment by Yoshiki-Iwasa** [comment]
修正済み。

原因　：　バックスラッシュによるエスケープのことをそもそも考えていなかった

**Comment by hiroin** [comment]
修正を確認しました。
