### ISSUE TITLE
環境変数の値の置き換えの動作相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#22]
事案
環境変数の値の置き換えの動作相違

miishellのver
464e47359e0778fb95b8fe57d4858799e7f22371

事案詳細
すでに設定されている環境変数について、testenv1=REPLACE_TEST1のようにコマンドを入力すると、bashの場合、環境変数の値が書き換わるが、minishellは書き換わらない

[bash]
```
$ export testenv1=TEST1
$ env | grep testenv1
testenv1=TEST1
$ testenv1=REPLACE_TEST1
$ env | grep testenv1
testenv1=REPLACE_TEST1
```
[minishell]
```
minishell$ export testenv1=TEST1
minishell$ env | grep testenv1
testenv1=TEST1
minishell$ testenv1=REPLACE_TEST1
minishell$ env | grep testenv1
testenv1=TEST1
```

**Comment by Yoshiki-Iwasa** [comment]
issue #5 とともに解消。

原因　；　シェル変数と環境変数が同時に置き換わることを知らなかった。

**Comment by hiroin** [comment]
修正を確認しました。
