### ISSUE TITLE
シェル変数に使えない文字の設定ができてしまう

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#23]
事案
シェル変数に使えない文字の設定ができてしまう

miishellのver
464e47359e0778fb95b8fe57d4858799e7f22371

事案詳細
[シェル変数の規約]
変数名に使える文字は、英数字または「 _ 」(アンダーバー)です。
先頭１文字目に数字は使えません。

minishellにおいて
TEST:
1TEST
という変数が設定できてしまう。

[bash]
```
$ testenv:=TEST
testenv:=TEST: command not found
$ 1testenv=TEST
1testenv=TEST: command not found

```
[minishell]
```
minishell$ testenv:=TEST
minishell$ 1testenv=TEST
```

**Comment by Yoshiki-Iwasa** [comment]
修正しました。

原因　：export  にはついていた条件処理がシェル変数にはついていなかった

**Comment by hiroin** [comment]
修正を確認しました。
