### ISSUE TITLE
>>で追記されない

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#26]
事案
\>\>で追記されない

miishellのver
d77b2ea449724f82e2416208ba985ae3c406580e

事案詳細
\>\>で追記されない

再現手順
[minishell]
```
minishell$ echo test >> a.txt
minishell$ cat a.txt
test
minishell$ echo test >> a.txt
minishell$ cat a.txt
test
```

**Comment by Yoshiki-Iwasa** [comment]
修正済み

原因　：　以前の複数リダイレクトに関する修正のとき、">>" の場合のopen関数の設定を間違って編集していた。

**Comment by hiroin** [comment]
修正を確認しました。
