### ISSUE TITLE
存在しないファイルを<で入力しようとした場合のメッセージ相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#29]
事案
存在しないファイルを<で入力しようとした場合のメッセージ相違

miishellのver
b7c97115eb72737ad38705c3a811e143ec850022

事案詳細
存在しないファイルを<で入力しようとした場合のエラーメッセージに相違がある
[bash]
bash: a.tx: No such file or directory

[minishell]
cat: -: Bad file descriptor
cat: closing standard input: Bad file descriptor

再現手順
[bash]
```
$ rm a.txt
$ cat < a.tx
$ ./ls
bash: a.tx: No such file or directory
```
[minishell]
```
$ rm a.txt
$ cat < a.tx
cat: -: Bad file descriptor
cat: closing standard input: Bad file descriptor
```

**Comment by Yoshiki-Iwasa** [comment]
修正しました〜

**Comment by hiroin** [comment]
修正を確認しました。
