### ISSUE TITLE
< ""した場合の動作相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#30]
事案
\< ""した場合の動作相違
※ https://github.com/Yoshiki-Iwasa/minishell/issues/29 を修正すれば、一緒に修正されそう…

miishellのver
b7c97115eb72737ad38705c3a811e143ec850022

事案詳細
```
cat < ""
```
とした場合、""というファイルの入力をしようとするため、No such file or directoryを表示する必要がある

再現手順
[bash]
```
$ cat < ""
bash: : No such file or directory
```
[minishell]
```
$ cat < ""
cat: -: Bad file descriptor
cat: closing standard input: Bad file descriptor
```

**Comment by Yoshiki-Iwasa** [comment]
issue #29 と一緒に修正済みです

**Comment by hiroin** [comment]
修正を確認しました。
