### ISSUE TITLE
$?の初期値相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#32]
事案
$?の初期値相違

miishellのver
b7c97115eb72737ad38705c3a811e143ec850022

事案詳細

bashの$?の初期値は0だが、minishellは1になっている
※guacamoleのbash3.2も0でした。zshは1でした。

再現手順
[bash]
```
bash
$ echo $?
0
```
[minishell]
```
 ./minishell
minishell$ echo $?
1
```

**Comment by Yoshiki-Iwasa** [comment]
修正済み

**Comment by hiroin** [comment]
修正を確認しました。
