### ISSUE TITLE
シェル変数/環境変数の値に\$を設定した場合の動作差異

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#33]
事案
シェル変数/環境変数の値に\$を設定した場合の動作差異

miishellのver
b7c97115eb72737ad38705c3a811e143ec850022

事案詳細

シェル変数/環境変数の値に\$を設定した場合、(おそらく)$を展開してしまう。

再現手順
[bash]
```
$ testenv1=\$value
$ echo $testenv1
$value
```
[minishell]
```
minishell$ testenv1=\$value
minishell$ echo $testenv1

```

**Comment by Yoshiki-Iwasa** [comment]
修正済み

**Comment by hiroin** [comment]
修正を確認しました。
