### ISSUE TITLE
echoの戻り値相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#35]
事案
echoの戻り値相違

miishellのver
b7c97115eb72737ad38705c3a811e143ec850022

事案詳細

bashおよびzshのechoコマンドの戻り値は0だが、minishellは1を返す。
※minishellだと/bin/echoの戻り値も1なのがなぜなのか分からないです…

再現手順
[bash]
```
$ echo a
a
$ echo $?
0
$ /bin/echo aaa
aaa
$ echo $?
0
```
[minishell]
```
minishell$ echo a
a
minishell$ echo $?
1
minishell$ /bin/echo aaa
aaa
minishell$ echo $?
1
```

**Comment by Yoshiki-Iwasa** [comment]
修正済み

原因は、echo コマンドを実行したときの返り値です。echo コマンドに関する返り値によってプログラムはecho の実行がうまくいったかどうかを検知してます。なので、echo コマンドの実態である関数の返り値をちょっといじればなおりました。

**Comment by hiroin** [comment]
/bin/echoはLinuxのコマンドなので、echoの戻り値はちゃんと0が返ってくると思ったのですが、/bin/echoとしても、組み込みコマンドのechoが実行されちゃってるかな…
https://github.com/Yoshiki-Iwasa/minishell/issues/28
の修正でそれも直るはずなので、こちらcloseします。
