### ISSUE TITLE
コマンド入力開始位置相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#36]
事案
コマンド入力開始位置相違

事案詳細
bashは、$の直後がコマンド入力位置だが、minishellは$の後ろにスペースが1つあって、その後ろがコマンド入力位置になっている

[bash]
```
$ls
 ↑
```

[minishell]
```
$ ls
  ↑
```

**Comment by Yoshiki-Iwasa** [comment]
```
user42@salty-VirtualBox:~$ bash
user42@salty-VirtualBox:~$ ps -p $$
  PID TTY          TIME CMD
 1775 pts/0    00:00:00 bash
user42@salty-VirtualBox:~$
```

自分のVM だとスペースあります。（^^ ;） どうしますか？

**Comment by hiroin** [comment]
おっと…失礼しました。
これは自分のミスです。
試験を作っている最中に、minishellとbashのコマンドプロンプトをあわせる作業で設定をしくじりました。
そのままでOKです。
