### ISSUE TITLE
パイプの後にechoコマンドを実行した際の出力相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#4]
事案
パイプの後にechoコマンドを実行した際の出力に相違がある

再現手順
```
$ cat stdout_and_stderr.sh 
echo "stdout" >&1
echo "stderr" >&2
```
[bash]
```
$ bash stdout_and_stderr.sh | echo

```
[minishell]
```
$ bash stdout_and_stderr.sh | echo
stderr

```
この動作は…なぜbashがstderrを出力しないのか分からないです…
類似案件で
```
$ cat stderr.sh 
echo "stderr" >&2
```
[bash]
```
$ bash stderr.sh | echo "b"
b
stderr
$ bash stderr.sh ; echo "b"
stderr
b

```
[minishell]
```
$ bash stderr.sh | echo "b"
stderr
b

```
bashはstdderを出力する前に、bを出力しています。
なぜそうなるのかわかりません…stderrがバッファされてるっぽいですよね
他のコマンドは問題なかったので、レビューする人がechoを使わないことを祈るしかないかな…
※teratailで聞いてみましょうか。

**Comment by Yoshiki-Iwasa** [comment]
これ、&> でなければうまくいきました。
とりあえず、保留でいきましょか

**Comment by hiroin** [comment]
> これ、&\> でなければうまくいきました。
具体的にどうすればいいですか。

\>&を使わない方法として
```
ls -l /zzz | echo b
```
を試してみました。
[minishell]
```
$ ls -l /zzz | echo b
ls: cannot access '/zzz': No such file or directory
b
```
[bash]
```
$ ls -l /zzz | echo b
b
ls: cannot access '/zzz': No such file or directory
```
bashは何かをバッファしている気がします…
/bin/echo(組み込みコマンドじゃないもの)でも同じ動作をするので、|とechoの組み合わせに何か秘密がある気がします。

**Comment by Yoshiki-Iwasa** [comment]
修正済み。

原因：親プロセスのコマンドが、子プロセスのコマンドの実行を待ってから実行される仕様になっていたこと。

`pipe.c`
の中の、`void	exec_pipes(int i, char ***args_array, int com_num, t_edlist *vals, char **paths)` 関数のなかに原因がありました。

**編集前**

```C　
void	exec_pipes(int i, char ***args_array, int com_num, t_edlist *vals, char **paths)
{
	pid_t ret;
	int rv;
	int pp[2] = {};
	if (i == com_num - 1)
	{
		// 左端なら単に実行
		rv = no_pipe(args_array[0], vals, paths);
		exit(rv);
	}
	else
	{
		// 左端以外ならpipeしてforkして親が実行、子が再帰
		pipe(pp);
		ret = fork();
		if (ret == 0)
		{
			// 子プロセスならパイプをstdoutにdup2してdopipes(i+1)で再帰し、
			// 次のforkで親になった側が右からi+1番目のコマンドを実行
			close(pp[0]);
			dup2(pp[1], 1);
			close(pp[1]);
			exec_pipes(i + 1, args_array, com_num, vals, paths);
			exit(0);
		}
		else
		{
				// 子プロセスの実行を待った後に
				// 親プロセスならパイプをstdinにdup2して、
				// 右からi番目のコマンドを実行
                                 wait(NULL);                                                      //   <- ここでwaitしていたため、子プロセスの終了を待ってから親プロセスが実行されていた。
				close(pp[1]);
				dup2(pp[0], 0);
				close(pp[0]);
				no_pipe(args_array[com_num -i -1], vals, paths); // <- コマンド実行
				exit(0);
		}
	}
```

**編集後**

```
else
		{
				// 子プロセスの実行を待った後に
				// 親プロセスならパイプをstdinにdup2して、
				// 右からi番目のコマンドを実行
                                //wait(NULL);   
				close(pp[1]);
				dup2(pp[0], 0);
				close(pp[0]);
				no_pipe(args_array[com_num -i -1], vals, paths); // <- コマンド実行
                                  wait(NULL);                                                        //<- wait をここに変えることで親プロセスが先に実行される。
				exit(0);
		}
```





**パイプがあった場合の挙動について。**

例えば、`ls | sort | wc` というコマンドの場合。
正しい場合、以下の順で処理が進んで行きます。



　　　　　         　                 ls           　         |                       sort                        |                              wc                
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
プロセス作成　　  |　　孫プロセス　　　　　　　　　　子プロセス　　　　　　　　　　　親プロセス
　    ↓
fork直後の状態　   |　　　  実行　　　　　<-　　孫プロセスの終了まち　　<-　　　子プロセスの終了まち

コマンドの状態　  |           標準出力　　　　|　　　　　標準入力まち　　　　|　　　　　　　標準入力まち
　　
fd の状態　　　　 |   標準入力=子の入り口   |　標準入力＝孫の標準出力 　　  |　　　　　標準入力=子の標準出力
　　　　　　　　　　　　　　　　　　　　      標準出力=親の入り口            
　　↓
孫実行後　　　　  |        標準出力　　　　->         入力get  -> 標準出力　　　->            　入力get -> 標準出力



修正前場合、以下の順で処理が進んで行きます。



　　　　　         　                    ls           　         |                       sort                        |                              wc                
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
プロセス作成　　  |　　孫プロセス　　　　　　　　　　子プロセス　　　　　　　　　　　親プロセス
　    ↓
fork直後の状態　   |　　　  実行　　　　　<-　　孫プロセスの終了まち　　<-　　　子プロセスの終了まち

コマンドの状態　  |           標準出力　　　　|　　　　　　　未実行　　　　　|　　　　　　　未実行
　　
fd の状態　　　　 |   標準入力=子の入り口   |　標準入力＝孫の標準出力 　　  |　　　　　標準入力=子の標準出力
　　　　　　　　　　　　　　　　　　　　      標準出力=親の入り口            
　　↓
孫実行後　　　　  |        標準出力　　　　->     コマンド実行->入力get -> 標準出力　->    コマンド実行->入力get -> 標準出力


なので、 修正前でも修正後でも標準入力を待つタイプのコマンドは、実行まえに入力が送られてくるので問題なかったんです。
でも、単純に出力する関数だと、実行順序が変わってしまうため、このようなissue が起きてました。

コマンドの右を親に、左を子にする理由は、最後に実行されるコマンドを親プロセスのコマンドにすることでゾンビプロセス（終了できずに生き続けるプロセス。ls  が親だとすると、最後のwc  が終了できたかどうかを感知できない。）が発生することを防ぎます。

**Comment by hiroin** [comment]
修正を確認しました。
また説明も理解しました。
ありがとうございます!
