### ISSUE TITLE
環境変数の値に空文字をセットした場合の動作相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#42]
事案
環境変数の値に空文字をセットした場合の動作相違

miishellのver
d142a3bb29d1a4f5414feb70934c16e2fd547b33

事案詳細
export testenv3=
とした際、キーがtestenv3、値が空文字の環境変数を設定しなければいけないが、minishellでは設定されない
おそらく
https://github.com/Yoshiki-Iwasa/minishell/issues/34
の改修の影響を受けているかもしれません。
条件分岐が難しそうです。
修正できそうですか。

再現手順
[bash]
```
$ export testenv3=
$ env | grep testenv3
testenv3=
$
```
[minishell]
```
minishell$ export testenv3=
minishell$ env | grep testenv3
minishell$ 
```

**Comment by Yoshiki-Iwasa** [comment]
修正しました！

**Comment by hiroin** [comment]
修正を確認しました。

**Comment by hiroin** [comment]
修正を確認しました。
