### ISSUE TITLE
[デグレ]echo "$testenv1"において、$testenv1が変数展開されない

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#46]
事案
echo "$testenv1"において、$testenv1が変数展開されない

事案詳細
[bash]
```
$ export testenv1=TEST1
$ echo "$testenv1"
TEST1
```
[minishell]
```
minishell$ export testenv1=TEST1
minishell$ echo "$testenv1"
$testenv1
```

**Comment by Yoshiki-Iwasa** [comment]
修正しました！

しかし、下の動作相違が解消できてません

```
bash-3.2$ $ddd
bash-3.2$ "$ddd"
bash: : command not found
bash-3.2$ 
```

```
minishell$ $ddd
minishell$ "$ddd"
minishell$ 
```

$ 変数がダブルクオートで囲われていたか否かで処理を分けるのが、意外と難関です。。。。。

**Comment by hiroin** [comment]
いつのまにか
bash-3.2$ $ddd
のケースも実現されてたんですね。すごい! 自分の「対応してないリスト」にありました。
bash-3.2$ "$ddd"は…、本質的な部分じゃないので対応しなくていいかなーって思います。
自分の「対応してないリスト」に記載して、テストケースにはもちろんいれないことにします。
