### ISSUE TITLE
Ctrl + \押下時の「^\」表示相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#47]
事案
Ctrl + \押下時の「^\」表示相違

miishellのver
5616c2600c403e92aec4656b0eebbcdadf6d0d3a

事案詳細
Ctrl + \\押下時に「\^\\」を表示するのはコマンド実行時のみ。
$ [Ctrl + \\]
および
$ cat [Ctrl + \\]
の場合は、何も表示しない。

[bash]
$ ここで [Ctrl + \\]
↓
$

$ cat ここで [Ctrl + \\]
↓
$ cat 

[minishell]
$ ここで [Ctrl +\ \]
↓
$^\\

$ cat ここで [Ctrl + \\]
↓
$ cat^\\

**Comment by Yoshiki-Iwasa** [comment]
issue #48 と一緒に解消済み

**Comment by hiroin** [comment]
修正を確認しました。
