### ISSUE TITLE
特定条件下でCtrl + \押下時にシグナルが送れていない(と思う)

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#48]
事案
特定条件下でCtrl + \押下時にシグナルが送れていない(と思う)

miishellのver
5616c2600c403e92aec4656b0eebbcdadf6d0d3a

事案詳細
特定条件下でCtrl + \押下時にシグナルが送れていない(と思う)

再現手順
```
$ [Ctrl + \を押す]
$ cat [Enter]
[Ctrl + \を押す]
```
2回目の[Ctrl + \を押す]でQuitして欲しいがQuitしてくれない

**Comment by Yoshiki-Iwasa** [comment]
修正済み

**Comment by hiroin** [comment]
動作修正OKです。
表示に「^\」が抜けてしまっているので追加をお願いします。

command_shell.c
```c
			if(WTERMSIG(status) == SIGQUIT)
			{
				if(WCOREDUMP(status))
					ft_putendl("^\\Quit: (core dumped)"); ← ここと
				else
					ft_putendl("^\\Quit"); ← ここ
			}
```

**Comment by Yoshiki-Iwasa** [comment]
ほんとだ
修正しました！

**Comment by hiroin** [comment]
修正を確認しました。
^\ってwriteするのではなくて、Ctrl + \すると、^\と打ち込まれているのに、\b\bで消してたということでいいのかな、たぶん。
