### ISSUE TITLE
「echo test$ test」のように、$の後が空白だったり改行だったりする場合は$をただの文字として認識する。

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#55]
事案
「echo test$ test」のように、$の後が空白だったり改行だったりする場合は$をただの文字として認識する。

miishellのver
0bb536aebb9927268584386ae7b03ee9ad3e5ed8

事案詳細
「echo test$ test」のように、$の後が空白だったり改行だったりする場合は$をただの文字として認識する。

再現手順

[bash]
```
$ echo a$
a$
$ echo $a$
$
$ echo a$a
a
$ echo test$ test
test$ test
```
[minishell]
```
minishell$ echo a$

minishell$ echo a
a
minishell$ echo a$

minishell$ echo $a$
minishell$ echo a$a
a
minishell$ echo test$ test
 test
```
実装できたら試験パターンに追加します…

**Comment by Yoshiki-Iwasa** [comment]
修正済みです。

追加の相違パターンをみつけてしまいました。

[bash]
```
bash-3.2$ test$ test
bash: test$: command not found
```
これも含めて修正済みです。

**Comment by hiroin** [comment]
修正を確認しました。
