### ISSUE TITLE
[デグレ]export testenv3=

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#56]
事案
[デグレ]export testenv3=

miishellのver
e714f4fe1625382e20c930fbdb8b7e5bce7d68d7

事案詳細
export testenv3=
としても環境変数がセットされない
testenv3=
export testenv3
とすればセットされる。

再現手順

[bash]
```
$ export testenv3=
$ env | grep testenv3
testenv3=
```
[minishell]
```
minishell$ export testenv3=
minishell$ env | grep testenv3
minishell$ testenv3=
minishell$ export testenv3
minishell$ env | grep testenv3
testenv3=
```

**Comment by Yoshiki-Iwasa** [comment]
修正しました。
010テスト実行済み

**Comment by hiroin** [comment]
修正を確認しました。
