### ISSUE TITLE
$ ctrl+Cおよび$ ls ctrl+C等、Enterを押す前にCtrl + Cをした場合、終了ステータスは130

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#57]
事案
$ ctrl+Cおよび$ ls ctrl+C等、Enterを押す前にCtrl + Cをした場合、終了ステータスは130

miishellのver
e714f4fe1625382e20c930fbdb8b7e5bce7d68d7

事案詳細
$ ctrl+C
$ ls ctrl+C
のように、Enterを押す前にCtrl + Cをした場合、終了ステータスは130になる

再現手順

[bash]
```
$ cat^C
$ echo $?
130
$ ^C
$ echo $?
130
```
[minishell]
```
$ cat^C
$ echo $?
0
$ ^C
$ echo $?
0
```

**Comment by Yoshiki-Iwasa** [comment]
結構むずい〜

**Comment by Yoshiki-Iwasa** [comment]
修正しました。。。。

**Comment by hiroin** [comment]
修正を確認しました。
