### ISSUE TITLE
[デグレ]$[Enter]と入力した場合、$: command not foundとならなくなった

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#58]
事案
[デグレ]$[Enter]と入力した場合、$: command not foundとならなくなった

miishellのver
e714f4fe1625382e20c930fbdb8b7e5bce7d68d7

miishellのver(OKだったVer、今日の朝のVer)
0bb536aebb9927268584386ae7b03ee9ad3e5ed8

事案詳細
$[Enter]と入力した場合、$: command not foundとならなくなった

再現手順

[bash]
```
$ $
$: command not found
$
```
[minishell]
```
minishell$ $
minishell$
```

すみません、なぜか自動試験の項目になくて、手動試験の項目にいれてました…

**Comment by Yoshiki-Iwasa** [comment]
修正しました。
test 010 実施済み

**Comment by hiroin** [comment]
修正を確認しました。
