### ISSUE TITLE
[セグフォ]$$aと入力するとセグフォする

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#59]
事案
[セグフォ]$$aと入力するとセグフォする

miishellのver
2d486f29069cddc606f31c60eecdcc176540863f

事案詳細
[セグフォ]$$aと入力するとセグフォする

再現手順

[minishell]
```
minishell$ $$$
[1]    22960 segmentation fault  ./minishell
minishell$ $$a
[1]    22975 segmentation fault  ./minishell
```

$$なので課題の範疇外なので、出力内容は任意でセグフォしないようにだけお願いします!
※int		translate_dollor_valiable(char **args, t_list *d_val, t_list *e_val)を見ていて思いついてしまいました…

**Comment by Yoshiki-Iwasa** [comment]
修正しました。

int		is_only_or_many_dollor(char *arg)

内で、２つ '$'  が重なったらreturn (1) させるようにしました

**Comment by hiroin** [comment]
修正を確認しました。
