### ISSUE TITLE
PATHをunsetしても、ルートディレクトリに実行ファイルを設置すると実行できてしまう

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#63]
事案
PATHをunsetしても、ルートディレクトリに実行ファイルを設置すると実行できてしまう

事案詳細
add_paths.c
の
char	**add_paths_and_change_arg0(char **argZero, t_edlist *vals)
において、return (add_new_path("/", paths));としている。
このため、PATHに何も入っていなくても、PATH=/の状態となり、例えば/bin/lsを/にコピーしておくと、lsとうつと、lsが実行できてしまう。
return (add_new_path(NULL, paths));でいいかなと思ったら、それでもlsが実行できてしまう…、すみません、修正方法が分からないです…

再現手順
[事前準備]
```
cp /bin/ls / ※特権が必要
```
[minishell]

```
minishell$ unset PATH
minishell$ ls
add_paths.c          command_pwd.c
以下略
```

**Comment by Yoshiki-Iwasa** [comment]
解消しました。
```
else if (paths[0][0] != '\0' && !(((*argZero)[0] == '.' || (*argZero)[0] == '/' ) && (*argZero)[1] != '\0'))
	{
		return (add_new_path("/", paths));
	}
	else
		return (paths);
```
としました

**Comment by hiroin** [comment]
PATHが設定できていない場合も/lsを実行できてしまっていました。
理由は、command_shell.cのchild_precess関数で、cmd_ptr = ft_strcat(command, "/");しているので、path[i]が\0でも、/が追加されて、/lsが実行できてしまっています。
path[i]が\0の場合、cmd_ptr = ft_strcat(command, "/");しない条件分岐が必要そうです。
```
		cmd_ptr = ft_strcat(command, paths[i]); //環境変数PATH を一個ずつ試す。
		cmd_ptr = ft_strcat(command, "/"); ← これが悪さしている
		cmd_ptr = ft_strcat(command, args[0]); //これで /user/bin/ls みたいにパスを完成させる。
		//相対パスと、絶対パスによる実行のために、コマンドの入力が スラッシュか、ピリオ土ではじまったときは、パスをpaths に追加した後、args[0]を編集する。
		printf("cmd_ptr = [%s]\n", cmd_ptr);  ← これで確認しました。
```

**Comment by Yoshiki-Iwasa** [comment]
PATH が設定されていないときでもルートディレクリにあれば実行できるのは問題ないのではないですか？？?
```
bash-3.2$ ./ls
ls OK
bash-3.2$ unset PATH
bash-3.2$ ls
ls OK
bash-3.2$ ./ls
ls OK
bash-3.2$ /ls
bash: /ls: No such file or directory
bash-3.2$ 
```

**Comment by Yoshiki-Iwasa** [comment]
修正しました。
```
	if (((*argZero)[0] == '.' || (*argZero)[0] == '/' ) && (*argZero)[1] != '\0' )
```
↓
```
	if (((*argZero)[0] == '.' || (*argZero)[0] == '/' ) && (*argZero)[1] != '\0' && paths[0][0] != '\0')
```

path が空文字列だけだったときは　"/" を追加するロジックに入れないようにしました。

**Comment by hiroin** [comment]
修正を確認しました。
