### ISSUE TITLE
標準入力したいファイルに書き込み権限がないと読み込めない

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#64]
事案
標準入力したいファイルに書き込み権限がないと読み込めない

事案詳細
change_fd.c
の
int		change_stdin_fd(char *arg, int *fd)
において、*fd = open(arg, O_RDWR);とO_RDWRにしている。
このため、開こうとしているファイルのパーミッションが0400(r------)の場合、openできない。
O_RDONLYに修正が必要。

再現手順
[minishell]

```
minishell$ touch test.txt
minishell$ chmod 400 test.txt
minishell$ cat < a.txt
bash: a.txt: No such file or directory
```

**Comment by Yoshiki-Iwasa** [comment]
初歩のミスですね 。。

修正しました！

**Comment by hiroin** [comment]
修正を確認しました。
