### ISSUE TITLE
[デグレ]cat < a.txt(存在しないファイル) > b.txtとすると処理が継続できなくなる

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#66]
事案
[デグレ]cat < a.txt(存在しないファイル) > b.txtとすると処理が継続できなくなる

事案詳細
cat < a.txt(存在しないファイル) > b.txtとすると処理が継続できなくなる

NGを確認したMinishellのVer(Date:   Mon Sep 7 09:36:10 2020)
a462b50aa143fcaf99d4830cd419640b04a45a78

OKを確認したMinishellのVer(Date:   Mon Sep 7 07:46:38 2020)
0bb536aebb9927268584386ae7b03ee9ad3e5ed8

再現手順
[minishell]

```
minishell$ rm a.txt
minishell$ cat < a.txt > b.txt
bash: a.txt: No such file or directory
(Ctrl + Cでも抜けられない)

```

**Comment by Yoshiki-Iwasa** [comment]
修正しました！

**Comment by hiroin** [comment]
修正を確認しました。
