### ISSUE TITLE
export a#=TESTのようにすると、環境変数に使えない変数をセットできてしまう

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#68]
事案
export a#=TESTのようにすると、環境変数に使えない変数をセットできてしまう

事案詳細
command_export.cのint		command_export(char **args, t_edlist *vals)関数において、exportする変数のチェックが先頭文字がアルファベットであることのみチェックしているので、環境変数に使えない変数をセットできてしまう。
check_key_str関数を追加すれば、たぶん、OK

再現手順
[bash]
```
$ export a#e=TEST
bash: export: `a#e=TEST': not a valid identifier
```
[minishell]

```
minishell$ export a#e=TEST
minishell$ env | grep a#e
a#e=TEST
```

**Comment by Yoshiki-Iwasa** [comment]
修正済み

**Comment by hiroin** [comment]
修正を確認しました。
