### ISSUE TITLE
[細かい案件]|を使った処理で応答が返ってこないケースがある

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#69]
事案
|を使った処理で応答が返ってこないケースがある

事案詳細
catすると表示に10秒くらいかかるテキストファイルを用意し、
```
cat longtxt.txt| wc -v
```
のように、big.txtをcatした出力をオプションが間違っているwc(例えば-v)に渡すと、応答が返ってこない。
Ctil + Cでも終了できない。

再現手順
[bash]
```
$ cat longtxt.txt | wc -v
wc: invalid option -- 'v'
Try 'wc --help' for more information.
$
```
[minishell]
```
minishell$ cat longtxt.txt | wc -v
wc: invalid option -- 'v'
Try 'wc --help' for more information.
(応答が返ってこない)
```
※|がある処理でCtrl + Cの動作を確認しようとして発見しました。
どう修正していいかわからないので、スルーしようと思います…

**Comment by Yoshiki-Iwasa** [comment]
うーん　とりあえず今出てるissue に対応するようにnorm 整形して、その上で対応可能そうだったらやります！

**Comment by hiroin** [comment]
OKですー、Closeいたします。
