### ISSUE TITLE
$?の値の相違

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#7]
事案
$?の値の相違

事案詳細
$?は、最後に実行されたフォアグラウンドのパイプラインの終了ステータスに展開される…つまり、最後に実行したコマンドの戻り値が格納される。
https://linuxjm.osdn.jp/html/GNU_bash/man1/bash.1.html
以下のケースにおいて、1が格納されていなければいけないが、0が返ってくる。
```
minishell$ ls
a.txt  ls.sh  minishell  stderr.sh  stdout_and_stderr.sh  stdout.log
minishell$ $ ls | grep "zzz" ; echo $?
0
```
grep "zzz"してもzzzはいないので、grepは1を返す(grepは検索した文字がない場合は1を返す)が、echo $?が1を表示しない。

再現手順
[bash]
```
$ ls | grep "zzz" ; echo $?
1
```
[minishell]
```
$ ls | grep "zzz" ; echo $?
0
```

**Comment by Yoshiki-Iwasa** [comment]
修正済み。

パイプが入ってた場合の終了ステータスの更新について考えていなかった。

**Comment by hiroin** [comment]
修正を確認しました。
