### ISSUE TITLE
[デグレ]セミコロンが動かなくなっている

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#79]
[事案]
セミコロンが動かなくなっている

[事案詳細]
```
minishell$ pwd ; pwd
/home/user42/42/minishell/test_bash
```
pwdが2回実行されるはずが、1回しか実行されない。

**Comment by Yoshiki-Iwasa** [comment]
あー、、、、これは、command_exit.c を修正したせいです
直します

**Comment by Yoshiki-Iwasa** [comment]
修正しました！

shell_exection.c の　　exec_each_command() で
```
if (!state || state <= 1000)
			break ;
↓
if (!state || state >= 1000)
			break ;
```

これが原因でした

**Comment by hiroin** [comment]
修正を確認しました。
pwd ; exit 100 ; pwd
のときは、exit 100で終わる必要があるので、上記ま分岐が必要なんですね。
