### ISSUE TITLE
/bin/lsがcommnad not foundとなる

### ISSUE THREAD

**Issue by hiroin** [Yoshiki-Iwasa/minishell#9]
事案
/bin/lsがcommnad not foundとなる。

事案詳細
/bin/lsがcommnad not foundとなる。
[https://github.com/Yoshiki-Iwasa/minishell/issues/1](https://github.com/Yoshiki-Iwasa/minishell/issues/1)
で対応済みかもですが、念の為isuueをたてておきます。

再現手順
[minishell]
```
minishell$ which ls
/bin/ls
minishell$ /bin/ls
bash: /bin/ls: commnad not found
```

**Comment by Yoshiki-Iwasa** [comment]
修正済み。

issue #1  修正時に完了してる。

**Comment by hiroin** [comment]
修正を確認しました。
